### PR TITLE
feat: Add Remix adapter

### LINKED ISSUE #1313: Support for Remix
Hello, I see that this project has Next.js support, however it is unclear whether Remix support is in the works or works out-of-the-box for the Next.js package. Are there perhaps any plans to include Remix (or, I guess since it is being merged with React Router, React Router) support?

Thank you, and I love this project so far! I can tell this will be extremely useful when I develop APIs in the future.

### PR DESCRIPTION
**Pull request by blaine-arcjet**
This adds a Remix adapter.

We provide a special `getLoadContext` export which is demonstrated in the example application. It currently looks up the IP from an Express or Deno server, but we're waiting on https://github.com/remix-run/remix/pull/10042 before their Deno plugin will provide the argument we need.

Closes #1313

### CODE REVIEW

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/undici@6.19.8
@SocketSecurity ignore npm/@remix-run/router@1.19.2
@SocketSecurity ignore npm/@remix-run/react@2.12.1

Remix stuff.

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/get-port@5.1.1

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/@remix-run/web-fetch@4.4.2

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/mime-db@1.53.0

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/validate-npm-package-name@5.0.1

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/normalize-package-data@5.0.0
@SocketSecurity ignore npm/npm-normalize-package-bin@3.0.1
@SocketSecurity ignore npm/which@3.0.1
@SocketSecurity ignore npm/@npmcli/promise-spawn@6.0.2

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/unique-slug@4.0.0
@SocketSecurity ignore npm/unique-filename@3.0.0
@SocketSecurity ignore npm/is-deflate@1.0.0
@SocketSecurity ignore npm/pidtree@0.6.0

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/diff@5.2.0

**Comment by davidmytton** [comment]
Looks good. We had one user asking about this as middleware rather than a loader and I provided the example to avoid any SSR in https://github.com/arcjet/arcjet-js/issues/1313#issuecomment-2367738862. Do we want to make that an official example?

**Comment by blaine-arcjet** [comment]
> Do we want to make that an official example?

I think it is fine to make it an official example, but it's really just how you use Express (middleware). I don't think we gain anything with it being an official example, so maybe we should add a section in the Remix reference that shows/links setting up Express middleware instead.

**Review by davidmytton — APPROVED** [review]

**Pull request merged**
