### PR TITLE
docs(examples): Updated to Clerk Core 2 (Clerk NextJS v5)

### PR DESCRIPTION
**Pull request by davidmytton**
Updates the Clerk examples following https://clerk.com/docs/upgrade-guides/core-2/overview

### CODE REVIEW

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/hasown@2.0.0
    @SocketSecurity ignore npm/@hono/node-server@1.10.1

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/eslint-config-custom@0.0.0
    @SocketSecurity ignore npm/@clerk/shared@2.0.0
    @SocketSecurity ignore npm/@clerk/clerk-react@5.0.1
    @SocketSecurity ignore npm/@clerk/backend@1.1.0

**Review by blaine-arcjet — CHANGES_REQUESTED** [review]
The added eslint-config-custom is a problem introduced by clerk in their monorepo. I don't think we should merge this or recommend them until it is fixed.

**Comment by davidmytton** [comment]
https://github.com/clerk/javascript/releases/tag/%40clerk%2Fclerk-react%405.0.4 has been released with the fix in https://github.com/clerk/javascript/pull/3307 so this should be good to go.

**Comment by blaine-arcjet** [comment]
We'll probably need to update the lockfile

**Comment by blaine-arcjet** [comment]
@SocketSecurity ignore npm/@clerk/backend@1.1.2
    @SocketSecurity ignore npm/@clerk/shared@2.0.2

**Review by blaine-arcjet — APPROVED** [review]
I've updated the clerk version to the version without problem and updated the lockfiles. Socket is now happy (except that clerk added a postinstall hook...)

**Pull request merged**
